disabled_rules:
  - cyclomatic_complexity
included:
  - Sources
excluded:
  - Pods

force_cast: warning
force_try:
  severity: warning # 显式

line_length: 120
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3 # 只是警告
  max_length: # 警告和错误
    warning: 40
    error: 50
  excluded: iPhone # 排除某个名字
identifier_name:
  min_length: # 只有最小长度
    warning: 1 # 只有错误
  excluded: # 排除某些名字
    - id
    - key
    - URL
    - GlobalAPIKey
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
